name: ReplayAddon-BW1058
main: dev.mrflyn.replayaddon.ReplayAddonMain
version: 0.0
api-version: 1.13
softdepend:
  - BedWars1058
  - AdvancedReplay
  - PlaceholderAPI
commands:
  rp:
    usage: /<command> []
    description: main command